
export const FONTS = {
  // Inter 18pt fonts
  Inter_18pt_Black: "Inter_18pt-Black",
  Inter_18pt_BlackItalic: "Inter_18pt-BlackItalic",
  Inter_18pt_Bold: "Inter_18pt-Bold",
  Inter_18pt_BoldItalic: "Inter_18pt-BoldItalic",
  Inter_18pt_ExtraBold: "Inter_18pt-ExtraBold",
  Inter_18pt_ExtraBoldItalic: "Inter_18pt-ExtraBoldItalic",
  Inter_18pt_ExtraLight: "Inter_18pt-ExtraLight",
  Inter_18pt_ExtraLightItalic: "Inter_18pt-ExtraLightItalic",
  Inter_18pt_Italic: "Inter_18pt-Italic",
  Inter_18pt_Light: "Inter_18pt-Light",
  Inter_18pt_LightItalic: "Inter_18pt-LightItalic",
  Inter_18pt_Medium: "Inter_18pt-Medium",
  Inter_18pt_MediumItalic: "Inter_18pt-MediumItalic",
  Inter_18pt_Regular: "Inter_18pt-Regular",
  Inter_18pt_SemiBold: "Inter_18pt-SemiBold",
  Inter_18pt_SemiBoldItalic: "Inter_18pt-SemiBoldItalic",
  Inter_18pt_Thin: "Inter_18pt-Thin",
  Inter_18pt_ThinItalic: "Inter_18pt-ThinItalic",

  // Inter 24pt fonts
  Inter_24pt_Black: "Inter_24pt-Black",
  Inter_24pt_BlackItalic: "Inter_24pt-BlackItalic",
  Inter_24pt_Bold: "Inter_24pt-Bold",
  Inter_24pt_BoldItalic: "Inter_24pt-BoldItalic",
  Inter_24pt_ExtraBold: "Inter_24pt-ExtraBold",
  Inter_24pt_ExtraBoldItalic: "Inter_24pt-ExtraBoldItalic",
  Inter_24pt_ExtraLight: "Inter_24pt-ExtraLight",
  Inter_24pt_ExtraLightItalic: "Inter_24pt-ExtraLightItalic",
  Inter_24pt_Italic: "Inter_24pt-Italic",
  Inter_24pt_Light: "Inter_24pt-Light",
  Inter_24pt_LightItalic: "Inter_24pt-LightItalic",
  Inter_24pt_Medium: "Inter_24pt-Medium",
  Inter_24pt_MediumItalic: "Inter_24pt-MediumItalic",
  Inter_24pt_Regular: "Inter_24pt-Regular",
  Inter_24pt_SemiBold: "Inter_24pt-SemiBold",
  Inter_24pt_SemiBoldItalic: "Inter_24pt-SemiBoldItalic",
  Inter_24pt_Thin: "Inter_24pt-Thin",
  Inter_24pt_ThinItalic: "Inter_24pt-ThinItalic",

  // Inter 28pt fonts
  Inter_28pt_Black: "Inter_28pt-Black",
  Inter_28pt_BlackItalic: "Inter_28pt-BlackItalic",
  Inter_28pt_Bold: "Inter_28pt-Bold",
  Inter_28pt_BoldItalic: "Inter_28pt-BoldItalic",
  Inter_28pt_ExtraBold: "Inter_28pt-ExtraBold",
  Inter_28pt_ExtraBoldItalic: "Inter_28pt-ExtraBoldItalic",
  Inter_28pt_ExtraLight: "Inter_28pt-ExtraLight",
  Inter_28pt_ExtraLightItalic: "Inter_28pt-ExtraLightItalic",
  Inter_28pt_Italic: "Inter_28pt-Italic",
  Inter_28pt_Light: "Inter_28pt-Light",
  Inter_28pt_LightItalic: "Inter_28pt-LightItalic",
  Inter_28pt_Medium: "Inter_28pt-Medium",
  Inter_28pt_MediumItalic: "Inter_28pt-MediumItalic",
  Inter_28pt_Regular: "Inter_28pt-Regular",
  Inter_28pt_SemiBold: "Inter_28pt-SemiBold",
  Inter_28pt_SemiBoldItalic: "Inter_28pt-SemiBoldItalic",
  Inter_28pt_Thin: "Inter_28pt-Thin",
  Inter_28pt_ThinItalic: "Inter_28pt-ThinItalic",
};

export const COLORS = {
  bgColor: '#FFFFFF',
  primary: 'rgba(37, 99, 235, 1)',
  white: '#FFFFFF',
  black: '#000000',
};
